### ISSUE TITLE
remove margin from page

### ISSUE THREAD

**Issue by dafcod16** [CarlosElizalde98/LandingPage#1]
Love everything about this landing page/project.
I messed around with some mozilla dev tools and added
`body{
    margin: 0px;
}`
to your css page and it removed that little bit of margin that left the edge of the webpage white. 
I think it makes it look that much better than it already is. 

Also "body" is different than ".body" so keep that in mind. when I added it to .body nothing happened.
Hope this helps!

**Comment by CarlosElizalde98** [comment]
Thank you for the feedback! I went ahead and changed the margin value to 0.
